# Generated by Django 3.2.13 on 2022-06-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
